# Generated by Django 3.0.8 on 2020-07-11 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200711_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='BlogProfile',
        ),
    ]
