# Generated by Django 3.0.8 on 2020-07-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200711_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogProfile',
        ),
    ]
